name = "agenda-link"
main = ".open-next/worker.js"
compatibility_date = "2026-10-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "agenda-link"

[[d1_databases]]
binding = "DB"
database_name = "agenda-link-db"
database_id = "cc3d3e2c-ce4c-46f5-b25e-b3e71a3fb611"
migrations_dir = "prisma/migrations"
migrations_pattern = "prisma/migrations/*/migration.sql"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "agenda-link-uploads"

[[ratelimits]]
name = "AUTH_RATE_LIMITER"
namespace_id = "10821001"
[ratelimits.simple]
limit = 10
period = 60

[[ratelimits]]
name = "ONBOARDING_RATE_LIMITER"
namespace_id = "10821002"
[ratelimits.simple]
limit = 5
period = 60

[[ratelimits]]
name = "BOOKING_RATE_LIMITER"
namespace_id = "10821003"
[ratelimits.simple]
limit = 20
period = 60

[[ratelimits]]
name = "SUPER_ADMIN_RATE_LIMITER"
namespace_id = "10821004"
[ratelimits.simple]
limit = 10
period = 60
