export interface BrandingFormState {
  landingTitle: string;
  setLandingTitle: (value: string) => void;
  landingSubtitle: string;
  setLandingSubtitle: (value: string) => void;
  landingAbout: string;
  setLandingAbout: (value: string) => void;
  landingCoverUrl: string;
  setLandingCoverUrl: (value: string) => void;
  landingSecondaryCoverUrl: string;
  setLandingSecondaryCoverUrl: (value: string) => void;
  logoUrl: string;
  setLogoUrl: (value: string) => void;
  landingPhone: string;
  setLandingPhone: (value: string) => void;
  landingAddress: string;
  setLandingAddress: (value: string) => void;
  landingHours: string;
  setLandingHours: (value: string) => void;
  feat1Title: string;
  setFeat1Title: (value: string) => void;
  feat1Desc: string;
  setFeat1Desc: (value: string) => void;
  feat2Title: string;
  setFeat2Title: (value: string) => void;
  feat2Desc: string;
  setFeat2Desc: (value: string) => void;
  feat3Title: string;
  setFeat3Title: (value: string) => void;
  feat3Desc: string;
  setFeat3Desc: (value: string) => void;
  test1Name: string;
  setTest1Name: (value: string) => void;
  test1Text: string;
  setTest1Text: (value: string) => void;
  test1Stars: number;
  setTest1Stars: (value: number) => void;
  test2Name: string;
  setTest2Name: (value: string) => void;
  test2Text: string;
  setTest2Text: (value: string) => void;
  test2Stars: number;
  setTest2Stars: (value: number) => void;
}
